### ISSUE TITLE
ERROR: 'rake/rdoctask' is obsolete...

### ISSUE THREAD

**Issue by omarkurt** [trevorturk/static#1]
Used command :  rake db:create

error : 
ERROR: 'rake/rdoctask' is obsolete and no longer supported. Use 'rdoc/task' (available in RDoc 2.4.2+) instead.

**Comment by trevorturk** [comment]
This project hasn't been updated in 3 years, so I wouldn't be surprised if some things are out of date. Sorry!

**Comment by omarkurt** [comment]
to give the right man! :)
